version: "2"
services:
  registry:
    image: registry:2
    expose:
      - "5000"
    volumes:
      - registry_data:/var/lib/registry:rw
  registry-gui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    links:
      - registry
    expose:
      - "80"
  nginx:
    build: ./nginx
    ports:
      - 5043:443
      - 80:80
    links:
      - registry
      - registry-gui
volumes:
  registry_data: {}