version: "2"
services:

  mandible:
    image: "girokon/mandible"
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /home/live/project/mandible:/etc/mandible:ro

  redis:
    image: redis
    restart: always
    ports:
     - 127.0.0.1:6379:6379

  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
    environment:
      ETCD_DATA_DIR: /var/lib/etcd
    volumes:
     - etcd:/var/lib/etcd:rw
    ports:
      - 127.0.0.1:2379:2379

  core:
    restart: always  
    image: dev.trendever.com:5000/master_core
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:4004:4004"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/core

  auth:
    restart: always  
    image: dev.trendever.com:5000/master_auth
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/auth

  api:
    restart: always  
    image: dev.trendever.com:5000/master_api
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "192.168.0.9:8085:8085"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/api
  
  mail:
    restart: always  
    image: dev.trendever.com:5000/master_mail
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/mail

  sms:
    restart: always  
    image: dev.trendever.com:5000/master_sms
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/sms

  chat:
    restart: always  
    image: dev.trendever.com:5000/master_chat
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/chat

  telebot:
    restart: always  
    image: dev.trendever.com:5000/master_telebot
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live2/telebot



volumes:
  etcd: {}
