version: "2"
services:


  nats:
    image: "nats"
    restart: always
    ports:
      - "192.168.0.7:4222:4222"

  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8086:8086
    volumes:
     - influxdata:/var/lib/influxdb:rw

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://trendever.com:3000
      GF_SECURITY_ADMIN_PASSWORD: "devsecretpass"

  redis:
    image: redis
    restart: always
    ports:
     - 192.168.0.7:6379:6379

  etcd:
    restart: always
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
    environment:
      ETCD_DATA_DIR: /var/lib/etcd
    volumes:
     - etcd:/var/lib/etcd:rw
    ports:
      - 127.0.0.1:2379:2379

  savetrend:
    restart: always  
    image: dev.trendever.com:5000/master_savetrend
    working_dir: /project
    volumes:
     - /home/live/bot-persistent:/var/persistent:rw
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/savetrend

  wantit:
    restart: always  
    image: dev.trendever.com:5000/master_wantit
    working_dir: /project
    volumes:
     - /home/live/bot-persistent:/var/persistent:rw
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/wantit

  core:
    restart: always  
    image: dev.trendever.com:5000/master_core
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:4004:4004"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/core

  auth:
    restart: always  
    image: dev.trendever.com:5000/master_auth
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/auth

  api:
    restart: always  
    image: dev.trendever.com:5000/master_api
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:8085:8085"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/api
  
  mail:
    restart: always  
    image: dev.trendever.com:5000/master_mail
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/mail

  sms:
    restart: always  
    image: dev.trendever.com:5000/master_sms
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/sms

  chat:
    restart: always  
    image: dev.trendever.com:5000/master_chat
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/chat

  telebot:
    restart: always  
    image: dev.trendever.com:5000/master_telebot
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/telebot

  payments:
    restart: always  
    image: dev.trendever.com:5000/master_payments
    working_dir: /project
    ports:
      - 127.0.0.1:7780:7780
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/payments

  elasticsync:
    restart: always
    image: dev.trendever.com:5000/master_elasticsync
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/elasticsync

  push:
    restart: always
    image: dev.trendever.com:5000/master_push
    working_dir: /project
    volumes:
     - /home/live/configs/apn:/var/persistent:ro
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/push

  mandible:
    restart: always  
    image: dev.trendever.com:5000/master_mandible
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live/mandible
    ports:
      - "192.168.0.7:8080:8080"

  elastic:
    restart: always
    image: elasticsearch:latest
    volumes:
      - elasticdata:/usr/share/elasticsearch:rw
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    command: elasticsearch

volumes:
  etcd: {}
  influxdata: {}
  elasticdata: {}
