version: "2"
services:
  nats:
    image: nats-streaming
    restart: always
    volumes:
      - natsdata:/data:rw
    entrypoint: /nats-streaming-server -st file -dir /data -cid stan -SD -ma 0s -mb 0 -mm 100000
    ports:
      - "192.168.0.7:4222:4222"
      - "127.0.0.1:8222:8222"
      - "127.0.0.1:4222:4222"
      - "10.8.0.1:4222:4222"
  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8086:8086
    volumes:
     - influxdata:/var/lib/influxdb:rw
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://trendever.com:3000
      GF_SECURITY_ADMIN_PASSWORD: "devsecretpass"
  redis:
    image: redis
    restart: always
    ports:
     - 192.168.0.7:6379:6379

  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
    restart: always
    environment:
      ETCD_DATA_DIR: /var/lib/etcd
    volumes:
     - etcd:/var/lib/etcd:rw
    ports:
      - 127.0.0.1:2379:2379

  core:
    restart: always  
    image: dev.trendever.com:5000/master_core
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:4004:4004"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/core

  trendcoin:
    restart: always
    image: dev.trendever.com:5000/master_trendcoin
    working_dir: /project
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/trendcoin

  checker:
    restart: always
    image: dev.trendever.com:5000/master_checker
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - /home/live/bot-persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/checker


  auth:
    restart: always  
    image: dev.trendever.com:5000/master_auth
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/auth

  api:
    restart: always  
    image: dev.trendever.com:5000/master_api
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:8085:8085"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/api
  
  mail:
    restart: always  
    image: dev.trendever.com:5000/master_mail
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/mail

  sms:
    restart: always  
    image: dev.trendever.com:5000/master_sms
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/sms

  push:
    restart: always
    image: dev.trendever.com:5000/master_push
    working_dir: /project
    volumes:
     - /home/live/configs/apn:/var/persistent:ro
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/push

  chat:
    restart: always  
    image: dev.trendever.com:5000/master_chat
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/chat

  savetrend:
    restart: always  
    image: dev.trendever.com:5000/master_savetrend
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - /home/live/bot-persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/savetrend

  wantit:
    restart: always  
    image: dev.trendever.com:5000/master_wantit
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - /home/live/bot-persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/wantit

  telebot:
    restart: always  
    image: dev.trendever.com:5000/master_telebot
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/telebot

  payments:
    restart: always  
    image: dev.trendever.com:5000/master_payments
    working_dir: /project
    ports:
      - 127.0.0.1:7780:7780
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/payments

  elasticsync:
    restart: always
    image: dev.trendever.com:5000/master_elasticsync
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/elasticsync

  accountstore:
    restart: always
    image: dev.trendever.com:5000/master_accountstore
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:5409:5409"
      - "10.8.0.1:5409:5409"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/accountstore

  elastic:
    restart: always
    image: elasticsearch:2
    volumes:
      - elasticdata:/usr/share/elasticsearch:rw
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    command: elasticsearch

  mandible:
    restart: always  
    image: dev.trendever.com:5000/master_mandible
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=live1/mandible
    ports:
      - "192.168.0.7:8080:8080"

volumes:
  influxdata: {}
  etcd: {}
  elasticdata: {}
  natsdata: {}
