version: "2"
services:
  mandible:
    image: "girokon/mandible"
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /home/live/project/mandible:/etc/mandible:ro
  nats:
    image: "nats"
    restart: always
    ports:
      - "127.0.0.1:4222:4222"