version: "2"
services:

  mandible:
    image: "girokon/mandible"
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /home/live/project/mandible:/etc/mandible:ro

  nats:
    image: "nats"
    restart: always
    ports:
      - "127.0.0.1:4222:4222"

  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8086:8086
    volumes:
     - influxdata:/var/lib/influxdb:rw

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://trendever.com:3000
      GF_SECURITY_ADMIN_PASSWORD: "devsecretpass"

  redis:
    image: redis
    restart: always
    ports:
     - 127.0.0.1:6379:6379

  etcd:
    image: quay.io/coreos/etcd:v2.3.0
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
    environment:
      ETCD_DATA_DIR: /data
    volumes:
     - etcd:/var/lib/etcd:rw
    ports:
      - 127.0.0.1:2379:2379

  core:
    restart: always  
    image: dev.trendever.com:5000/master_core
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.auth:
    restart: always  
    image: dev.trendever.com:5000/master_service.auth
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.public.api:
    restart: always  
    image: dev.trendever.com:5000/master_service.public.api
    working_dir: /project
    ports:
      - "8085:8085"
    environment:
      - CONSUL_HOST=consul:8500
  
  service.mail:
    restart: always  
    image: dev.trendever.com:5000/master_service.mail
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.sms:
    restart: always  
    image: dev.trendever.com:5000/master_service.sms
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.chat:
    restart: always  
    image: dev.trendever.com:5000/master_service.chat
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.telebot:
    restart: always  
    image: dev.trendever.com:5000/master_service.telebot
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.wantit:
    restart: always  
    image: dev.trendever.com:5000/master_service.wantit
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.savetrend:
    restart: always  
    image: dev.trendever.com:5000/master_service.savetrend
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

  service.ig.inbox.fetcher:
    restart: always  
    image: dev.trendever.com:5000/master_service.ig.inbox.fetcher
    working_dir: /project
    environment:
      - CONSUL_HOST=consul:8500

volumes:
  influxdata: {}
  etcd: {}
