version: "2"
services:
  nats:
    image: nats-streaming
    restart: always
    volumes:
      - natsdata:/data:rw
    entrypoint: /nats-streaming-server -st file -dir /data -cid stan -SD -ma 0s -mb 0 -mm 100000
    ports:
      - "127.0.0.1:4222:4222"

  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8086:8086
    volumes:
     - influxdata:/var/lib/influxdb:rw

  redis:
    image: redis
    restart: always
    ports:
     - 127.0.0.1:6379:6379

  core:
    restart: always  
    image: dev.trendever.com:5000/services/dev_core
    working_dir: /project
    ports:
      - "127.0.0.1:4004:4004"
    volumes:
     - /home/dev/config/core:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  trendcoin:
    restart: always
    image: dev.trendever.com:5000/services/dev_trendcoin
    working_dir: /project
    volumes:
     - /home/dev/config/trendcoin:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  checker:
    restart: always
    image: dev.trendever.com:5000/services/dev_checker
    working_dir: /project
    volumes:
     - /home/dev/persistent:/var/persistent:rw
     - /home/dev/config/checker:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  auth:
    restart: always  
    image: dev.trendever.com:5000/services/dev_auth
    working_dir: /project
    volumes:
     - /home/dev/config/auth:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  api:
    restart: always  
    image: dev.trendever.com:5000/services/dev_api
    working_dir: /project
    ports:
      - "127.0.0.1:8085:8085"
    volumes:
     - /home/dev/config/api:/project/config:ro
  
  mail:
    restart: always  
    image: dev.trendever.com:5000/services/dev_mail
    working_dir: /project
    volumes:
     - /home/dev/config/mail:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  sms:
    restart: always  
    image: dev.trendever.com:5000/services/dev_sms
    working_dir: /project
    volumes:
     - /home/dev/config/sms:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  chat:
    restart: always  
    image: dev.trendever.com:5000/services/dev_chat
    working_dir: /project
    volumes:
     - /home/dev/config/chat:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  savetrend:
    restart: always  
    image: dev.trendever.com:5000/services/dev_savetrend
    working_dir: /project
    volumes:
     - /home/dev/persistent:/var/persistent:rw
     - /home/dev/config/savetrend:/project/config:ro

  wantit:
    restart: always  
    image: dev.trendever.com:5000/services/dev_wantit
    working_dir: /project
    volumes:
     - /home/dev/persistent:/var/persistent:rw
     - /home/dev/config/wantit:/project/config:ro

  telebot:
    restart: always  
    image: dev.trendever.com:5000/services/dev_telebot
    working_dir: /project
    volumes:
     - /home/dev/config/telebot:/project/config:ro

  payments:
    restart: always  
    image: dev.trendever.com:5000/services/dev_payments
    working_dir: /project
    ports:
      - 127.0.0.1:7780:7780
    volumes:
     - /home/dev/config/payments:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  elasticsync:
    restart: always
    image: dev.trendever.com:5000/services/dev_elasticsync
    working_dir: /project
    volumes:
     - /home/dev/config/elasticsync:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  accountstore:
    restart: always
    image: dev.trendever.com:5000/services/dev_accountstore
    working_dir: /project
    ports:
      - "127.0.0.1:5409:5409"
    volumes:
     - /home/dev/config/accountstore:/project/config:ro
    extra_hosts:
     - "db:172.17.0.1"

  elastic:
    restart: always
    image: elasticsearch:2
    volumes:
      - elasticdata:/usr/share/elasticsearch:rw
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    command: elasticsearch

  mandible:
    restart: always  
    image: dev.trendever.com:5000/services/dev_mandible
    working_dir: /project
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /home/dev/config/mandible:/project/config:ro

  fetcher:
    restart: always
    image: dev.trendever.com:5000/services/dev_fetcher
    working_dir: /project
    volumes:
      - /home/dev/config/fetcher:/project/config:ro
    extra_hosts:
      - "db:172.17.0.1"


volumes:
  natsdata: {}
  influxdata: {}
  elasticdata: {}

