version: "2"
services:
  nats:
    image: nats-streaming
    restart: always
    volumes:
      - natsdata:/data:rw
    entrypoint: /nats-streaming-server -st file -dir /data -cid stan -SD -ma 0s -mb 0 -mm 100000
    ports:
      - "8222:8222"
      - "127.0.0.1:4222:4222"
  influxdb:
    image: influxdb:alpine
    restart: always
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8086:8086
    volumes:
     - influxdata:/var/lib/influxdb:rw
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://dev.trendever.com:3000
      GF_SECURITY_ADMIN_PASSWORD: "devsecretpass"
  redis:
    image: redis
    restart: always
    ports:
     - 127.0.0.1:6379:6379

  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
    restart: always
    environment:
      ETCD_DATA_DIR: /var/lib/etcd
    volumes:
     - etcd:/var/lib/etcd:rw
    ports:
      - 127.0.0.1:2379:2379

  core:
    restart: always  
    image: dev.trendever.com:5000/dev_core
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:4004:4004"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/core

  trendcoin:
    restart: always
    image: dev.trendever.com:5000/dev_trendcoin
    working_dir: /project
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/trendcoin

  checker:
    restart: always
    image: dev.trendever.com:5000/dev_checker
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/checker


  auth:
    restart: always  
    image: dev.trendever.com:5000/dev_auth
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/auth

  api:
    restart: always  
    image: dev.trendever.com:5000/dev_api
    working_dir: /project
    depends_on:
      - etcd
    ports:
      - "127.0.0.1:8085:8085"
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/api
  
  mail:
    restart: always  
    image: dev.trendever.com:5000/dev_mail
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/mail

  sms:
    restart: always  
    image: dev.trendever.com:5000/dev_sms
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/sms

  push:
    restart: always
    image: dev.trendever.com:5000/dev_push
    working_dir: /project
    volumes:
     - persistent:/var/persistent:ro
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/push

  chat:
    restart: always  
    image: dev.trendever.com:5000/dev_chat
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/chat
    ports:
      - "127.0.0.1:2010:2010"

  fetcher:
    restart: always  
    image: dev.trendever.com:5000/dev_fetcher
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/fetcher
    ports:
      - "127.0.0.1:4015:4015"

  savetrend:
    restart: always  
    image: dev.trendever.com:5000/dev_savetrend
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/savetrend

  wantit:
    restart: always  
    image: dev.trendever.com:5000/dev_wantit
    working_dir: /project
    depends_on:
      - etcd
    volumes:
     - persistent:/var/persistent:rw
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/wantit

  telebot:
    restart: always  
    image: dev.trendever.com:5000/dev_telebot
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/telebot

  payments:
    restart: always  
    image: dev.trendever.com:5000/dev_payments
    working_dir: /project
    ports:
      - 127.0.0.1:7777:7777
      - 127.0.0.1:7780:7780
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/payments

  elasticsync:
    restart: always
    image: dev.trendever.com:5000/dev_elasticsync
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/elasticsync

  accountstore:
    restart: always
    image: dev.trendever.com:5000/dev_accountstore
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/accountstore

  db:
    restart: always
    image: "postgres:9.3"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata:rw
    ports:
      - "127.0.0.1:5432:5432"

  elastic:
    restart: always
    image: elasticsearch:2
    volumes:
      - elasticdata:/usr/share/elasticsearch:rw
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    command: elasticsearch

  mandible:
    restart: always  
    image: dev.trendever.com:5000/dev_mandible
    working_dir: /project
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
      - ETCD_PATH=dev/mandible
    ports:
      - "127.0.0.1:8089:8089"

volumes:
  influxdata: {}
  etcd: {}
  dbdata: {}
  elasticdata: {}
  persistent: {}
  natsdata: {}

