version: "2"
services:

  fetcher:
    restart: always  
    image: dev.trendever.com:5000/master_fetcher
    working_dir: /project
    network_mode: "host"
    ports:
      - "127.0.0.1:4410:4410"
      - "10.8.0.6:4410:4410"
    volumes:
    - /home/trendever/config:/project/config:ro

