version: "2"
services:
  core:
    restart: always
    image: dev.trendever.com:5000/cryptobot/dev_core
    volumes:
      - ${CONFIGS_PATH}/cryptobot/core.yaml:/core.yaml:ro
    depends_on:
      - db
      - rabbit

  telegram:
    restart: always
    image: dev.trendever.com:5000/cryptobot/dev_telegram
    volumes:
      - ${CONFIGS_PATH}/cryptobot/telegram.yaml:/telegram.yaml:ro
    depends_on:
      - db
      - rabbit

  api:
    restart: always
    image: dev.trendever.com:5000/cryptobot/dev_api
    volumes:
      - ${CONFIGS_PATH}/cryptobot/api.yaml:/api.yaml:ro
    depends_on:
      - rabbit
    ports:
      - 127.0.0.1:8083:8083

  db:
    restart: always
    image: "postgres:9-alpine"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata:rw
    ports:
      - 127.0.0.1:5433:5432

  rabbit:
    restart: always
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "bun"
      RABBITMQ_DEFAULT_PASS: "alert"
    volumes:
      - rabbitdata:/var/lib/rabbitmq:rw
    ports:
      - 127.0.0.1:5672:5672
      # managment web interface
      - 127.0.0.1:8070:15672

volumes:
  dbdata: {}
  rabbitdata: {}
